modLoader="javafml" 
loaderVersion="[36,)"
license="MIT"
[[mods]]  
modId="sovereign"  
version="0.0.1"  
displayName="Summoner Sovereign"
authors="IVANDEV"
description='''
Indev version of upcoming Summoner mod.
'''

[[dependencies.summonersovereign]]
    modId="forge"  
    mandatory=true  
    versionRange="[36,)"  
    ordering="NONE"
    side="BOTH"
[[dependencies.summonersovereign]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"